spring:
  application:
    name: app

db:
  uri:  ${MONGODB_CLIENT_URI-:mongodb://localhost:27017/}
  name: ${MONGODB_DB_NAME-:wearpark-dev}

auth:
  providers:
    email-password:
      max-attempts: 5
      lockout-duration: t5m
  jwt:
    secret: ${JWT_SECRET-:dev-secret-abcedefghijklmnopqrstuvwxyz}
    expiration: 1d

netty:
  port: 9000
  server-cert-path: src/main/resources/server-test.crt
  server-key-path:  src/main/resources/server-test.key
  ca-cert-path:     src/main/resources/ca-test.crt
  ca-key-path:      src/main/resources/ca-test.key
